[package]
name = "studipfs"
version = "0.1.0"
authors = ["tibequadorian <tibequadorian@posteo.de>"]
edition = "2018"

[dependencies]
fuser = "0.11"
libc = "*"
minreq = { version = "2.6", features = ["https", "json-using-serde"] }
serde = { version = "1.0", features = ["derive"] }
ttl_cache = "0.5"
